FROM nginx:1.20-alpine

RUN apk update && apk upgrade
RUN apk add bash
RUN apk add bash-completion
RUN apk add iputils
RUN apk add net-tools
RUN apk add procps
RUN apk add dos2unix
RUN apk add vim
## install telnet
RUN apk add busybox-extras

RUN mkdir -p /nginx-confd
RUN mkdir -p /etc/nginx/templates
